### ISSUE TITLE
MacOS Issues solution

### ISSUE THREAD

**Issue by aminya** [KyleMayes/install-llvm-action#15]
I have been trying to fix the MacOS issues, and I was finally able to fix it. I think this can become a part of the action itself to remove the need for an excess step.

```yaml
      - name: MacOS - Prepare LLVM
        if: contains(matrix.os, 'macos')
        run: |
          LLVM_PATH=${{ env.LLVM_PATH }}
          LLVM_VERSION=${{ matrix.clang }}
          ## already done inside install-llvm-action
          # echo "PATH="$LLVM_PATH:$PATH"
          # echo "LD_LIBRARY_PATH=$LLVM_PATH/lib/:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          # echo "DYLD_LIBRARY_PATH=$LLVM_PATH/lib/:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV
          echo "CPATH=$LLVM_PATH/lib/clang/$LLVM_VERSION/include/" >> $GITHUB_ENV
          echo "LDFLAGS=-L$LLVM_PATH/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$LLVM_PATH/include" >> $GITHUB_ENV
          echo "CC=$LLVM_PATH/bin/clang" >> $GITHUB_ENV
          echo "CXX=$LLVM_PATH/bin/clang++" >> $GITHUB_ENV
```

**Comment by Morwenn** [comment]
This workaround used to work with the `macos-10.15` environment, but after I switched to `macos-11` it started failing again with the following error messages:

```
In file included from /Users/runner/work/cpp-sort/cpp-sort/llvm/bin/../include/c++/v1/algorithm:641:
In file included from /Users/runner/work/cpp-sort/cpp-sort/llvm/bin/../include/c++/v1/cstring:60:
/Users/runner/work/cpp-sort/cpp-sort/llvm/bin/../include/c++/v1/string.h:73:64: error: use of undeclared identifier 'strchr'
char* __libcpp_strchr(const char* __s, int __c) {return (char*)strchr(__s, __c);}
                                                               ^
/Users/runner/work/cpp-sort/cpp-sort/llvm/bin/../include/c++/v1/string.h:80:75: error: use of undeclared identifier 'strpbrk'
char* __libcpp_strpbrk(const char* __s1, const char* __s2) {return (char*)strpbrk(__s1, __s2);}
```

I couldn't figure what was wrong, so I temporarily gave up on using older versions of Clang on MacOS.

**Comment by aminya** [comment]
Try setup-cpp that supports installing llvm:
https://github.com/aminya/setup-cpp

**Comment by KyleMayes** [comment]
This action mainly exists to support https://github.com/KyleMayes/clang-sys and friends and I've not faced this issue.
So if folks have whatever this problem is I'd recommend either checking out https://github.com/aminya/setup-cpp or opening a PR.
